linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - goimports
    - gosec
    - errcheck
    - gosimple
    - unused
    - typecheck
    - nolintlint
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar  # replaced exportloopref
    - forcetypeassert
    - godot
    - makezero
    - nilerr
    - predeclared
    - usetesting  # replaced tenv
    - thelper
    - tparallel
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable:
      - shadow  # replaced check-shadowing
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:  # replaced run.skip-dirs
    - vendor
    - testdata
  exclude-files:  # replaced run.skip-files
    - ".*_test.go"

run:
  timeout: 5m