version: '3.8'

services:
  katago-mcp:
    image: ghcr.io/dmmcquay/katago-mcp:latest
    container_name: katago-mcp
    restart: unless-stopped
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Network configuration
    ports:
      - "8080:8080"  # Health check endpoint
    
    # Environment variables
    environment:
      - KATAGO_MCP_LOG_LEVEL=info
      - KATAGO_LOG_FORMAT=json
      - KATAGO_HTTP_PORT=8080
      
    # Volume mounts for configuration and models
    volumes:
      # Custom configuration (optional)
      - ./config/production.json:/app/config/config.json:ro
      
      # Custom models (optional)
      # - ./models:/app/models:ro
      
      # Logs (optional)
      # - ./logs:/app/logs
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M
    
    # User specification (non-root)
    user: "1000:1000"
    
    # Labels for management
    labels:
      - "com.docker.compose.project=katago-mcp"
      - "traefik.enable=false"  # Disable if using Traefik
      
networks:
  default:
    driver: bridge
    
# Optional: Add a reverse proxy for production
# nginx:
#   image: nginx:alpine
#   container_name: katago-mcp-proxy
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     - ./ssl:/etc/ssl:ro
#   depends_on:
#     - katago-mcp