name: Build KataGo Base Image

on:
  # Manual trigger only - we don't want this running on every commit
  workflow_dispatch:
    inputs:
      katago_version:
        description: 'KataGo version to build'
        required: true
        default: 'v1.14.1'
        type: string
  
  # Also trigger on changes to the base image files
  push:
    paths:
      - 'docker/katago-base/**'
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dmmcquay/katago-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ inputs.katago_version || 'v1.14.1' }}
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: docker/katago-base
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          KATAGO_VERSION=${{ inputs.katago_version || 'v1.14.1' }}

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}