name: Build KataGo Base Image

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      katago_version:
        description: 'KataGo version to build (e.g., v1.14.1)'
        required: true
        default: 'v1.14.1'
        type: string
      push:
        description: 'Push image to registry'
        required: true
        default: true
        type: boolean
  
  # Trigger on changes to the base image
  push:
    branches: [main]
    paths:
      - 'docker/katago-base/**'
      - '.github/workflows/build-katago-base.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dmmcquay/katago-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ inputs.katago_version }}"
        else
          VERSION="v1.14.1"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: docker/katago-base
        platforms: linux/amd64
        push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          KATAGO_VERSION=${{ steps.version.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test image
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      run: |
        docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} katago version