name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache: true
    
    - name: Check formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Code is not formatted. Run 'go fmt ./...' to fix."
          gofmt -d .
          exit 1
        fi
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x']
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Upload coverage to Codecov
      if: matrix.go-version == '1.22.x'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt
        fail_ci_if_error: false
        verbose: true

  edge-case-tests:
    name: Edge Case Tests
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache: true
    
    - name: Run edge case tests
      run: |
        if [ -f scripts/run-edge-case-tests.sh ]; then
          chmod +x scripts/run-edge-case-tests.sh
          ./scripts/run-edge-case-tests.sh
        else
          echo "No edge case tests found, skipping..."
        fi

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    container:
      image: ghcr.io/dmmcquay/katago-base:v1.14.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache: true
    
    - name: Verify KataGo is available
      run: |
        echo "🔍 Checking KataGo installation..."
        which katago
        katago version || true
    
    - name: Set up KataGo test environment
      run: |
        echo "📥 Setting up KataGo model and config..."
        mkdir -p ~/.katago
        
        # Install curl and build tools for CGO
        apt-get update && apt-get install -y curl build-essential
        
        # Download a small test model
        curl -L -o ~/.katago/test-model.bin.gz \
          https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b18c384nbt-s9996604416-d4316597426.bin.gz
        
        # Generate analysis config with default settings (non-interactive)
        echo "chinese" | katago genconfig -model ~/.katago/test-model.bin.gz -output ~/.katago/analysis.cfg
        
        # Verify files exist
        ls -la ~/.katago/
    
    - name: Run integration tests
      run: |
        echo "🧪 Running integration tests with real KataGo..."
        # Enable CGO for race detection
        export CGO_ENABLED=1
        go test -v -tags=integration -race ./internal/katago/...
        echo "✅ Integration tests completed"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test, integration-tests]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache: true
    
    - name: Build
      run: ./build.sh
    
    - name: Test binary
      run: |
        ./katago-mcp -version || true
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: katago-mcp-linux-amd64
        path: katago-mcp

  e2e-tests:
    name: E2E Tests (Docker)
    runs-on: ubuntu-latest
    needs: [lint, test, integration-tests]
    permissions:
      contents: read
      packages: write  # Needed to push images if building base
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check if base image exists
      id: check-base
      run: |
        echo "🔍 Checking if KataGo base image exists..."
        if docker pull ghcr.io/dmmcquay/katago-base:v1.14.1; then
          echo "✅ Base image found"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Base image not found, will build it"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Set up Docker Buildx
      if: steps.check-base.outputs.exists == 'false'
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push base image if needed
      if: steps.check-base.outputs.exists == 'false'
      uses: docker/build-push-action@v5
      with:
        context: docker/katago-base
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/dmmcquay/katago-base:v1.14.1
          ghcr.io/dmmcquay/katago-base:latest
        build-args: |
          KATAGO_VERSION=v1.14.1
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Download model for E2E tests
      run: |
        echo "📥 Downloading neural network model..."
        mkdir -p docker/katago-artifacts
        # Download a model from katagotraining.org (same as our download script)
        curl -L -o docker/katago-artifacts/test-model.bin.gz \
          https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b18c384nbt-s9996604416-d4316597426.bin.gz
    
    - name: Build and run E2E tests in Docker
      run: |
        echo "🐳 Building Docker image for E2E tests..."
        
        # Build the e2e test image (will use pre-built base)
        docker build -f Dockerfile.e2e -t katago-mcp-e2e .
        
        echo "🔍 Validating Docker image..."
        ./scripts/validate-docker-image.sh
        
        echo "🧪 Running E2E tests in Docker container..."
        docker run --rm katago-mcp-e2e
        
        echo "✅ E2E tests completed successfully"


  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && github.event_name == 'push'
      with:
        sarif_file: 'trivy-results.sarif'